/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.recorddb.server;

import com.recorddb.core.DatabaseOperations;
import com.recorddb.core.NoSQLDatabase;
import com.recorddb.command.CommandExecutor;

import java.util.Scanner;
import java.util.concurrent.CompletableFuture;
import java.util.logging.Logger;


public class App {
    private static final Logger LOGGER = Logger.getLogger(App.class.getName());

    public static void main(String[] args) {
        // Initialize database and command executor
        DatabaseOperations database = new NoSQLDatabase();
        CommandExecutor executor = new CommandExecutor(database);
        Scanner scanner = new Scanner(System.in);

        while (true) {
            String input = scanner.nextLine().trim();

            if (input.equalsIgnoreCase("exit")) {
                break;
            }

            try {
                CompletableFuture<String> future = executor.executeCommand(input);
                String result = future.join();
                System.out.println(result);

                if (result.contains("Adios")) {
                    break;
                }
            } catch (Exception e) {
                System.out.println("Error: " + e.getMessage());
            }
        }

        scanner.close();
    }
}
